#!/bin/bash

cd `dirname $0`/..
CODEQ_VERSION="0.1.0-SNAPSHOT"
CODEQ_ROOT=`pwd`

DATOMIC_VERSION="0.8.3784"
DATOMIC_FILE="datomic-free-$DATOMIC_VERSION"
DATOMIC_URL=http://downloads.datomic.com/$DATOMIC_VERSION/$DATOMIC_FILE.zip

BACKUP_FILE="clojure-and-contrib"
BACKUP_URL=http://codeq.s3.amazonaws.com/examples/$BACKUP_FILE.zip

DB_URI="datomic:free://localhost:4334/clojure-and-contrib"

RET=0

WORKING_DIR=tmp/examples/clojure-and-contrib
mkdir -p $WORKING_DIR
cd $WORKING_DIR
WORKING_DIR=`pwd`

if [ ! -d "$BACKUP_FILE" ]; then
  wget $BACKUP_URL
  unzip $BACKUP_FILE.zip
fi

if [ ! -d "$DATOMIC_FILE" ]; then
  wget $DATOMIC_URL
  unzip $DATOMIC_FILE.zip
fi

#### Restore

cd $DATOMIC_FILE

# Start with a fresh database
rm -rf data log

bin/transactor config/samples/free-transactor-template.properties &
TRANSACTOR_PID=$!

(( RET += $? ))

bin/datomic restore-db file:$WORKING_DIR/$BACKUP_FILE $DB_URI

(( RET += $? ))

pkill -P $TRANSACTOR_PID

#### Verify

bin/transactor config/samples/free-transactor-template.properties &
TRANSACTOR_PID=$!

(( RET += $? ))

cd $CODEQ_ROOT

sleep 5

lein run -m datomic.codeq.examples.clojure-and-contrib $DB_URI

(( RET += $? ))

cd $CODEQ_ROOT
lein clean
lein uberjar

git clone git@github.com:clojure/clojure.git $WORKING_DIR/clojure
cd $WORKING_DIR/clojure

java -server -Xmx1g -jar $CODEQ_ROOT/target/codeq-$CODEQ_VERSION-standalone.jar $DB_URI

(( RET += $? ))

pkill -P $TRANSACTOR_PID

exit $RET
